apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: nginx-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nginx-app-v1
  policy:
    semver:
      range: 0.0.x
